### PR TITLE
PSP22: Update selectors and add the `Result` in the signature of methods

### PR DESCRIPTION
**Pull request by xgreenx**
Update selectors according to PSP22 naming of the interface(previous selectors were generated for PSP20).
Added the `Result` in the signature of the methods, because based on a conversation in the [issue](https://github.com/paritytech/ink/issues/641) we finalized, how revert will work and how we can return the data during the revert to the caller(and finalized how it can be implemented during cross contract calls).

### CODE REVIEW

**Review by cmichi — APPROVED** [review]

**Comment by themarkian** [comment]
Hey @cmichi @Noc2 @athei!
I see that you approved changes on this PR. Let's have it merged if you are okay. 
We would love to move the process forward :)

**Comment by xlc** [comment]
This format is really hard to read due to the ABI defs. It will be better if there is a at glance view of everything. Simply moving ABI to bottom of the file is also helpful.

**Comment by xgreenx** [comment]
> This format is really hard to read due to the ABI defs. It will be better if there is a at glance view of everything. Simply moving ABI to bottom of the file is also helpful.

I agree with you, that it is hard to read. Do you have ideas of how to make it more readable?
As a solution, we can add an example of how types described in the `defs` section can be represented(implemented) in Rust.

**Comment by Noc2** [comment]
Sounds good, I will merge the updates, but feel free to continue to improve readability.

**Pull request merged**
