### PR TITLE
PSP-7: Polkadot DKG threshold multisig wallet

### PR DESCRIPTION
**Pull request by VadimGrznk**

### CODE REVIEW

**Comment by burdges** [comment]
https://github.com/w3f/schnorrkel/issues/5#issuecomment-631386178

**Comment by VadimGrozinok** [comment]
Hi!

**Comment by VadimGrozinok** [comment]
Hi!
Good point, thanks.
Will have a look at it.

**Comment by VadimGrznk** [comment]
Hi!
Good point, thanks.
Will have a look at it.

**Comment by burdges** [comment]
It's a difference between asking devs to build the collection code themselves and read them all at once (starsig) vs imposing some collection code (schnorrkel).  It's hard to make flexibility user friendly though, so maybe best to stick with schnorrkel's way.

**Comment by Noc2** [comment]
This should be PSP number 7 (=7th PR to the repo) instead of 2.

**Comment by VadimGrznk** [comment]
Yes, already changed it.

**Comment by burdges** [comment]
I've no idea how well this aligns with whatever we'll eventually implement, but if folks want to merge this as a draft then we can do so, or we can keep this open for notes whenever this get implemented.

**Comment by lamafab** [comment]
Merging as part of #40.

**Pull request closed without merging**
